[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
shared = { path = "../shared/", develop = true }
native = { path = "../native/" }
pytiled-parser = "^2.2.2"
pillow = "^9.5.0"
betterproto = { git = "https://github.com/kilimnik/python-betterproto.git", rev="pickle", extras = ["compiler"] }
collision = "^1.2.2"
dill = "^0.3.6"
dataclasses_jsonschema = "^2.16.0"
mazelib = { git = "https://github.com/john-science/mazelib.git", rev="242c27c58241636c5c4ceb2d2ab46dd7ed86c293" }
aiohttp-retry = "^2.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
server = "server.main:run"
debugger = "server.main:debug"