## defaults for _all_ profiles
[default]
address = "0.0.0.0"
limits = { form = "64 kB", json = "1 MiB" }
port = 4444

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }
