[package]
name = "cryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.5"
block-modes = "0.8.1"
hex-literal = "0.3.4"
hex = "0.4.3"
rand = "0.8.4"
md-5 = "0.10.0"