version: "3.7"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.4
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init-db.sh:ro